apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      {{ if .Values.persistent_volume }}
      volumes:
        - name: {{ .Values.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.name }}
      {{ end }}
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagepull }}
          env:
          # digi info
          - name: GROUP
            value: {{ .Values.group }}
          - name: VERSION
            value: {{ .Values.version }}
          - name: PLURAL
            value: {{ .Values.plural }}
          - name: Kind
            value: {{ .Values.kind }}
          - name: NAME
            value: {{ .Values.name }}
          - name: NAMESPACE
            value: {{ .Values.namespace }}
          # configurations
          - name: MOUNTER
            value: {{ quote .Values.mounter }}
          - name: LOGLEVEL
            value: {{ .Values.log_level | default 20 | quote }}
          # pool
          - name: LAKE_PROVIDER
            value: {{ .Values.lake_provider | default "zed" }}
          - name: LAKE
            value: {{ .Values.lake | default "http://lake:6534" }}
          - name: ZED_LAKE # for backward compatibility TBD deprecate in v0.3
            value: {{ .Values.zed_lake | default "http://lake:6534" }}
          # composition
          - name: MOUNT_MODE
            value: {{ quote .Values.mount_mode }}
          - name: TRIM_MOUNT_ON_LOAD
            value: {{ quote .Values.trim_mount_on_load }}
          # visualization
          - name: VISUAL
            value: {{ quote .Values.visual }}
          - name: VISUAL_TYPE
            value: {{ quote .Values.visual_type }}
          - name: VISUAL_REFRESH_INTERVAL
            value: {{ .Values.visual_refresh_interval | default 1000 | quote }}
          ports:
          - containerPort: 7534
            name: visual
          - containerPort: 5540
            protocol: UDP
            name: matter
          - containerPort: 5353
            protocol: UDP
            name: mdns

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
    app: digi
spec:
  ports:
  - port: 7534
    targetPort: 7534
    protocol: TCP
    name: visual
  - port: 5540
    targetPort: 5540
    protocol: UDP
    name: matter
  - port: 5353
    targetPort: 5353
    protocol: UDP
    name: mdns
  selector:
    name: {{ .Values.name }}