{{ if .Values.persistent_volume }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: {{ .Values.persistent_volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistent_volume.path }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent_volume.size }}

---

{{ end }}