apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
      app: headscale
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
        app: headscale
    spec:
      serviceAccountName: {{ .Values.name }}
      volumes:
        - name: {{ .Values.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagepull }}
          env:
          - name: GROUP
            value: {{ .Values.group }}
          - name: VERSION
            value: {{ .Values.version }}
          - name: PLURAL
            value: {{ .Values.plural }}
          - name: NAME
            value: {{ .Values.name }}
          - name: NAMESPACE
            value: {{ .Values.namespace }}
          - name: MOUNTER
            value: {{ quote .Values.mounter }}
          - name: LOGLEVEL
            value: {{ .Values.log_level | default "20" | quote }}
          - name: LAKE_PROVIDER
            value: {{ .Values.lake_provider | default "zed" }}
          - name: LAKE
            value: {{ .Values.lake | default "http://lake:6534" }}
          - name: ZED_LAKE # for backward compatibility TBD deprecate in v0.3
            value: {{ .Values.zed_lake | default "http://lake:6534" }}
          ports: # https://github.com/juanfont/headscale/blob/main/docs/running-headscale-container.md
          - containerPort: 8080 # Web UI
          - containerPort: 9090 # Metrics
          volumeMounts:
          - mountPath: /var/lib/headscale/
            name: {{ .Values.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
    app: headscale
spec:
  type: NodePort
  ports: # headscale
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 30100
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    nodePort: 30101
    protocol: TCP
  selector:
    name: {{ .Values.name }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: {{ .Values.persistent_volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistent_volume.path }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistent_volume.size }}
