apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lakes.digi.dev
spec:
  group: digi.dev
  names:
    kind: lake
    listKind: lakeList
    plural: lakes
    singular: lake
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              control:
                properties:
                  poll_interval:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                type: object
              pools:
                additionalProperties:
                  properties:
                    head:
                      type: string
                    last_updated:
                      type: string
                    name:
                      type: string
                    size:
                      type: number
                  type: object
                type: object
              stats:
                properties:
                  num_pools:
                    type: number
                type: object
            type: object
        type: object
    served: true
    storage: true
